const routes = {
  files: "/files",
  groups: "/groups",
  home: "/home",
  chat: "/chat",
  planner: "/planner",
  innerCameras: "/inner-cameras",
  innerChat: "/inner-chat",
  innerConfiguration: "/inner-configuration",
  innerFiles: "/inner-files",
  innerHistory: "/inner-history",
  innerPlanner: "/inner-planner",
  innerStatistic: "/inner-statistic",
  login: "/login",
  logs: "/logs",
  manageStore: "/manage-store",
  setting: "/setting",
  storeInfo: "/store-info",
  users: "/users",
  forgotPassword: "/forgot-password",
  newPassword: "/new-password",
  emailSend: "/email-send",
  mcdStores: "/mcd-stores",
};

export default routes;
