const routes = {
  home: "/stores",
  scripts: "/scripts",
  scriptsEdit: "/scripts/:id/mode=edit",
  scriptsLaunch: "/scripts/:id/mode=launch",
  groups: "/groups",
  chat: "/chat/:id",
  planner: "/planner",
  innerCameras: "/stores/inner-cameras",
  innerChat: "/stores/inner-chat",
  innerConfiguration: "/stores/inner-configuration",
  innerFiles: "/stores/inner-files",
  innerHistory: "/stores/inner-history",
  innerPlanner: "/stores/inner-planner",
  innerStatistic: "/stores/inner-statistic",
  innerTickets: "/stores/inner-tickets",
  innerSchedule: "/stores/inner-schedule",
  innerBusiness: "/stores/inner-business",
  tickets: "/tickets",
  login: "/login",
  logs: "/logs",
  scripts_logs: "/scripts-logs",
  manageStore: "/stores/manage-store",
  setting: "/setting",
  storeInfo: "/stores/store-info",
  users: "/users",
  forgotPassword: "/forgot-password",
  newPassword: "/new-password",
  emailSend: "/email-send",
  mcdStores: "/mcd-stores",
};

export default routes;
