const routes = {
  home: "/stores",
  files: "/files",
  groups: "/groups",
  chat: "/chat",
  planner: "/planner",
  innerCameras: "/stores/inner-cameras",
  innerChat: "/stores/inner-chat",
  innerConfiguration: "/stores/inner-configuration",
  innerFiles: "/stores/inner-files",
  innerHistory: "/stores/inner-history",
  innerPlanner: "/stores/inner-planner",
  innerStatistic: "/stores/inner-statistic",
  login: "/login",
  logs: "/logs",
  manageStore: "/stores/manage-store",
  setting: "/setting",
  storeInfo: "/stores/store-info",
  users: "/users",
  forgotPassword: "/forgot-password",
  newPassword: "/new-password",
  emailSend: "/email-send",
  mcdStores: "/mcd-stores",
};

export default routes;
